### ISSUE TITLE
Retravailler la neige

### ISSUE THREAD

**Issue by LionelPaulus** [nansthomas/hetic-p2019-09#19]

**Comment by nansthomas** [comment]
[Snow Folder](https://drive.google.com/drive/u/1/folders/0B014T_sH3lXYOTYxUEVKMWdTVDg)

**Comment by nansthomas** [comment]
<img width="851" alt="screen shot 2016-11-23 at 16 21 01" src="https://cloud.githubusercontent.com/assets/9898339/20567419/e3c56d34-b198-11e6-88dd-b7b1e127995d.png">

Il faut régler ce problème... @ThaddeMeneur
